// packages/nuxt/src/runtime/components/AbnxtAdmin.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import type { AbConfig, Experiment, Variant } from '@abnxt/core';
import {
  toggleActive,
  setField,
  addExperiment,
  removeExperiment,
  upsertExperiment,
  normalizeToPercents,
  addVariant,
  removeVariant,
  setWeight,
  simulateSplit,
  setOverride,
  clearOverride,
  serializeConfig,
  parseConfigJson,
  apiStorage,
} from '@abnxt/core/admin';

const props = withDefaults(
  defineProps<{
    configEndpoint?: string;
    authEndpoint?: string;
    title?: string;
  }>(),
  {
    configEndpoint: '/api/abnxt/config',
    authEndpoint: '/api/abnxt/auth',
    title: 'abnxt admin',
  },
);

type Status = 'loading' | 'gate' | 'ready';

const status = ref<Status>('loading');
const config = ref<AbConfig | null>(null);
const selectedKey = ref<string | null>(null);
const dirty = ref(false);
const message = ref<string | null>(null);
const gateKey = ref('');
const gateError = ref<string | null>(null);
const gateBusy = ref(false);

const storage = computed(() => apiStorage({ base: props.configEndpoint }));

const experimentEntries = computed<[string, Experiment][]>(() => {
  const c = config.value;
  if (!c || typeof c !== 'object' || !c.experiments) return [];
  return Object.entries(c.experiments);
});

const selected = computed<Experiment | null>(() => {
  const c = config.value;
  if (!c || selectedKey.value == null) return null;
  return c.experiments[selectedKey.value] ?? null;
});

// 렌더 경로 예외 금지: 정규화/시뮬레이션은 try/catch 폴백(React와 동일).
const selectedPercents = computed<Record<string, number>>(() => {
  const exp = selected.value;
  if (!exp) return {};
  try {
    return normalizeToPercents(exp.variants);
  } catch {
    return {};
  }
});

const simulation = computed<{ key: string; count: number; pct: number }[]>(
  () => {
    const exp = selected.value;
    if (!exp) return [];
    try {
      const counts = simulateSplit(exp, 1000);
      return Object.entries(counts).map(([key, count]) => ({
        key,
        count,
        pct: Math.round((count / 1000) * 100),
      }));
    } catch {
      return [];
    }
  },
);

function splitLabel(exp: Experiment): string {
  try {
    const pcts = normalizeToPercents(exp.variants);
    return Object.entries(pcts)
      .map(([k, v]) => `${k} ${v}%`)
      .join(' / ');
  } catch {
    return '';
  }
}

// --- 데이터 로드 / 인증 (브라우저 전용: onMounted) ---

async function loadConfigFromServer(): Promise<void> {
  try {
    const res = await fetch(props.configEndpoint, {
      credentials: 'same-origin',
      headers: { accept: 'application/json' },
    });
    if (res.status === 401) {
      status.value = 'gate';
      return;
    }
    if (!res.ok) {
      status.value = 'gate';
      gateError.value = `Failed to load config (${res.status})`;
      return;
    }
    const raw: unknown = await res.json();
    // 렌더 경로 예외 금지: parseConfigJson(core 검증·정규화·폴백) 경유(React와 동일).
    const parsed = parseConfigJson(JSON.stringify(raw));
    config.value = parsed.config;
    dirty.value = false;
    status.value = 'ready';
    const keys = Object.keys(parsed.config.experiments);
    if (selectedKey.value == null || !keys.includes(selectedKey.value)) {
      selectedKey.value = keys[0] ?? null;
    }
    message.value =
      !parsed.ok && parsed.message
        ? `Loaded with warning: ${parsed.message}`
        : null;
  } catch {
    status.value = 'gate';
    gateError.value = 'Network error while loading config';
  }
}

async function submitKey(): Promise<void> {
  gateError.value = null;
  gateBusy.value = true;
  try {
    const res = await fetch(props.authEndpoint, {
      method: 'POST',
      credentials: 'same-origin',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ key: gateKey.value }),
    });
    if (!res.ok) {
      gateError.value = 'Invalid key';
      return;
    }
    gateKey.value = '';
    await loadConfigFromServer();
  } catch {
    gateError.value = 'Network error';
  } finally {
    gateBusy.value = false;
  }
}

async function logout(): Promise<void> {
  try {
    await fetch(props.authEndpoint, {
      method: 'DELETE',
      credentials: 'same-origin',
    });
  } catch {
    // 무시: 쿠키는 만료 응답으로 제거되며 실패해도 키폼 복귀.
  }
  config.value = null;
  selectedKey.value = null;
  dirty.value = false;
  message.value = null;
  status.value = 'gate';
}

onMounted(() => {
  void loadConfigFromServer();
});

// --- 편집 (모두 @abnxt/core/admin 함수 경유) ---

function markDirty(next: AbConfig): void {
  config.value = next;
  dirty.value = true;
  message.value = null;
}

function onAddExperiment(): void {
  const c = config.value;
  if (!c) return;
  const before = new Set(Object.keys(c.experiments));
  const next = addExperiment(c);
  markDirty(next);
  const created = Object.keys(next.experiments).find((k) => !before.has(k));
  if (created) selectedKey.value = created;
}

function onRemoveExperiment(key: string): void {
  const c = config.value;
  if (!c) return;
  const next = removeExperiment(c, key);
  markDirty(next);
  if (selectedKey.value === key) {
    selectedKey.value = Object.keys(next.experiments)[0] ?? null;
  }
}

function onToggleActive(key: string): void {
  const c = config.value;
  if (!c) return;
  markDirty(toggleActive(c, key));
}

function onSelect(key: string): void {
  selectedKey.value = key;
}

function onSetField(
  fields: Partial<Pick<Experiment, 'name' | 'sticky' | 'seed' | 'control'>>,
): void {
  const c = config.value;
  if (!c || selectedKey.value == null) return;
  markDirty(setField(c, selectedKey.value, fields));
}

function updateSelectedVariants(variants: Variant[]): void {
  const c = config.value;
  const exp = selected.value;
  if (!c || !exp || selectedKey.value == null) return;
  // setField는 variants를 다루지 않으므로 upsertExperiment로 변이 배열을 반영.
  markDirty(upsertExperiment(c, selectedKey.value, { ...exp, variants }));
}

function onAddVariant(): void {
  const exp = selected.value;
  if (!exp) return;
  updateSelectedVariants(addVariant(exp.variants));
}

function onRemoveVariant(key: string): void {
  const exp = selected.value;
  if (!exp) return;
  updateSelectedVariants(removeVariant(exp.variants, key));
}

function onSetWeight(key: string, weight: number): void {
  const exp = selected.value;
  if (!exp) return;
  updateSelectedVariants(setWeight(exp.variants, key, weight));
}

// --- Preview (override 쿠키) ---

function onPreview(variant: string): void {
  if (selectedKey.value == null) return;
  setOverride(selectedKey.value, variant);
  message.value = `Preview set: ${selectedKey.value} → ${variant}`;
}

function onClearPreview(): void {
  if (selectedKey.value == null) return;
  clearOverride(selectedKey.value);
  message.value = `Preview cleared: ${selectedKey.value}`;
}

// --- 저장 / Export / Import ---

async function onSave(): Promise<void> {
  const c = config.value;
  if (!c) return;
  try {
    await storage.value.save(c);
    dirty.value = false;
    message.value = 'Saved.';
  } catch (e) {
    message.value = `Save failed: ${(e as Error).message}`;
  }
}

function onExport(): void {
  const c = config.value;
  if (!c) return;
  const json = serializeConfig(c);
  if (typeof document === 'undefined') return;
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'abnxt-config.json';
  a.click();
  URL.revokeObjectURL(url);
}

function onImportFile(e: Event): void {
  const input = e.target as HTMLInputElement;
  const file = input.files?.[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = () => {
    const text = String(reader.result ?? '');
    const result = parseConfigJson(text);
    if (!result.ok) {
      message.value = `Import failed: ${result.message ?? 'invalid config'}`;
      return;
    }
    config.value = result.config;
    dirty.value = true;
    selectedKey.value = Object.keys(result.config.experiments)[0] ?? null;
    message.value = 'Imported (not yet saved).';
  };
  reader.readAsText(file);
  input.value = '';
}
</script>

<template>
  <div class="abnxt-admin">
    <!-- 로딩 -->
    <div
      v-if="status === 'loading'"
      class="abnxt-admin__empty"
    >
      Loading…
    </div>

    <!-- 키 입력 게이트 -->
    <div
      v-else-if="status === 'gate'"
      class="abnxt-admin__gate"
    >
      <div class="abnxt-admin__title">{{ title }}</div>
      <p>Enter the admin key to continue.</p>
      <form @submit.prevent="submitKey">
        <input
          v-model="gateKey"
          class="abnxt-admin__gate-input"
          type="password"
          placeholder="Admin key"
          autocomplete="current-password"
        />
        <button
          class="abnxt-admin__btn abnxt-admin__btn--primary"
          type="submit"
          :disabled="gateBusy"
        >
          Unlock
        </button>
      </form>
      <div
        v-if="gateError"
        class="abnxt-admin__error"
      >
        {{ gateError }}
      </div>
    </div>

    <!-- 인증된 화면 -->
    <template v-else>
      <div class="abnxt-admin__header">
        <div class="abnxt-admin__title">{{ title }}</div>
        <button
          class="abnxt-admin__btn"
          type="button"
          @click="onAddExperiment"
        >
          + Experiment
        </button>
        <button
          class="abnxt-admin__btn"
          type="button"
          @click="onExport"
        >
          Export
        </button>
        <label class="abnxt-admin__btn">
          Import
          <input
            type="file"
            accept="application/json"
            style="display: none"
            @change="onImportFile"
          />
        </label>
        <button
          class="abnxt-admin__btn"
          :class="{ 'abnxt-admin__btn--dirty': dirty }"
          type="button"
          :disabled="!dirty"
          @click="onSave"
        >
          Save
        </button>
        <button
          class="abnxt-admin__btn"
          type="button"
          @click="logout"
        >
          Logout
        </button>
      </div>

      <div
        v-if="message"
        class="abnxt-admin__msg"
      >
        {{ message }}
      </div>

      <div class="abnxt-admin__body">
        <!-- 좌측 리스트 -->
        <div class="abnxt-admin__list">
          <div
            v-if="experimentEntries.length === 0"
            class="abnxt-admin__empty"
          >
            No experiments yet.
          </div>
          <div
            v-for="[key, exp] in experimentEntries"
            :key="key"
            class="abnxt-admin__list-item"
            :class="{
              'abnxt-admin__list-item--selected': key === selectedKey,
            }"
            @click="onSelect(key)"
          >
            <div class="abnxt-admin__list-main">
              <div class="abnxt-admin__list-name">{{ exp.name || key }}</div>
              <div class="abnxt-admin__list-key">{{ key }}</div>
              <div class="abnxt-admin__list-split">{{ splitLabel(exp) }}</div>
            </div>
            <button
              class="abnxt-admin__btn"
              type="button"
              aria-label="active"
              @click.stop="onToggleActive(key)"
            >
              {{ exp.active ? 'on' : 'off' }}
            </button>
          </div>
        </div>

        <!-- 우측 에디터 -->
        <div class="abnxt-admin__editor">
          <div
            v-if="!selected"
            class="abnxt-admin__empty"
          >
            Select an experiment to edit.
          </div>
          <template v-else>
            <div class="abnxt-admin__field">
              <label>name</label>
              <input
                class="abnxt-admin__input"
                type="text"
                :value="selected.name"
                @input="
                  onSetField({
                    name: ($event.target as HTMLInputElement).value,
                  })
                "
              />
            </div>
            <div class="abnxt-admin__field">
              <label>active</label>
              <input
                type="checkbox"
                :checked="selected.active"
                @change="selectedKey && onToggleActive(selectedKey)"
              />
            </div>
            <div class="abnxt-admin__field">
              <label>sticky</label>
              <input
                type="checkbox"
                :checked="selected.sticky"
                @change="
                  onSetField({
                    sticky: ($event.target as HTMLInputElement).checked,
                  })
                "
              />
            </div>
            <div class="abnxt-admin__field">
              <label>seed</label>
              <input
                class="abnxt-admin__input"
                type="text"
                :value="selected.seed"
                @input="
                  onSetField({
                    seed: ($event.target as HTMLInputElement).value,
                  })
                "
              />
            </div>
            <div class="abnxt-admin__field">
              <label>control</label>
              <select
                class="abnxt-admin__input"
                :value="selected.control"
                @change="
                  onSetField({
                    control: ($event.target as HTMLSelectElement).value,
                  })
                "
              >
                <option
                  v-for="v in selected.variants"
                  :key="v.key"
                  :value="v.key"
                >
                  {{ v.key }}
                </option>
              </select>
            </div>

            <!-- variants -->
            <div
              v-for="v in selected.variants"
              :key="v.key"
              class="abnxt-admin__variant"
            >
              <!-- variant key는 읽기전용(rename은 sticky/배정에 영향 + 원본에 없음). -->
              <span class="abnxt-admin__variant-key">{{ v.key }}</span>
              <input
                type="range"
                min="0"
                max="100"
                :value="v.weight"
                @input="
                  onSetWeight(
                    v.key,
                    Number(($event.target as HTMLInputElement).value),
                  )
                "
              />
              <span class="abnxt-admin__variant-pct"
                >{{ selectedPercents[v.key] ?? 0 }}%</span
              >
              <button
                class="abnxt-admin__btn"
                type="button"
                @click="onPreview(v.key)"
              >
                Preview
              </button>
              <button
                class="abnxt-admin__btn"
                type="button"
                @click="onClearPreview"
              >
                Clear
              </button>
              <button
                class="abnxt-admin__btn abnxt-admin__btn--danger"
                type="button"
                @click="onRemoveVariant(v.key)"
              >
                ×
              </button>
            </div>
            <button
              class="abnxt-admin__btn"
              type="button"
              @click="onAddVariant"
            >
              + Variant
            </button>

            <!-- 시뮬레이션 -->
            <div class="abnxt-admin__sim">
              <div class="abnxt-admin__list-split">Simulation (1000 users)</div>
              <div
                v-for="row in simulation"
                :key="row.key"
                class="abnxt-admin__sim-row"
              >
                <span class="abnxt-admin__variant-key">{{ row.key }}</span>
                <span
                  class="abnxt-admin__sim-bar"
                  :style="{ width: row.pct * 2 + 'px' }"
                />
                <span class="abnxt-admin__variant-pct">{{ row.count }}</span>
              </div>
            </div>

            <div
              class="abnxt-admin__field"
              style="margin-top: 16px"
            >
              <button
                class="abnxt-admin__btn abnxt-admin__btn--danger"
                type="button"
                @click="selectedKey && onRemoveExperiment(selectedKey)"
              >
                Delete
              </button>
            </div>
          </template>
        </div>
      </div>
    </template>
  </div>
</template>

<style>
.abnxt-admin {
  font-family:
    system-ui,
    -apple-system,
    sans-serif;
  color: #111;
  max-width: 1100px;
  margin: 0 auto;
  padding: 16px;
}

.abnxt-admin *,
.abnxt-admin *::before,
.abnxt-admin *::after {
  box-sizing: border-box;
}

.abnxt-admin__header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding-bottom: 12px;
  border-bottom: 1px solid #e5e7eb;
  margin-bottom: 12px;
  flex-wrap: wrap;
}

.abnxt-admin__title {
  font-size: 16px;
  font-weight: 700;
  margin-right: auto;
}

.abnxt-admin__btn {
  font: inherit;
  padding: 6px 10px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  background: #fff;
  cursor: pointer;
}

.abnxt-admin__btn:hover {
  background: #f9fafb;
}

.abnxt-admin__btn:disabled {
  opacity: 0.5;
  cursor: default;
}

.abnxt-admin__btn--primary {
  background: #2563eb;
  border-color: #2563eb;
  color: #fff;
}

.abnxt-admin__btn--primary:hover {
  background: #1d4ed8;
}

.abnxt-admin__btn--danger {
  color: #dc2626;
  border-color: #fca5a5;
}

.abnxt-admin__btn--dirty {
  background: #2563eb;
  border-color: #2563eb;
  color: #fff;
}

.abnxt-admin__msg {
  padding: 8px 12px;
  border-radius: 6px;
  background: #f3f4f6;
  margin-bottom: 12px;
  font-size: 13px;
}

.abnxt-admin__body {
  display: grid;
  grid-template-columns: 280px 1fr;
  gap: 16px;
}

.abnxt-admin__list {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.abnxt-admin__list-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  cursor: pointer;
  background: #fff;
}

.abnxt-admin__list-item--selected {
  background: #eff6ff;
  border-color: #93c5fd;
}

.abnxt-admin__list-main {
  display: flex;
  flex-direction: column;
  min-width: 0;
  margin-right: auto;
}

.abnxt-admin__list-name {
  font-weight: 600;
  font-size: 13px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.abnxt-admin__list-key {
  font-size: 11px;
  color: #6b7280;
}

.abnxt-admin__list-split {
  font-size: 11px;
  color: #6b7280;
}

.abnxt-admin__editor {
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 16px;
}

.abnxt-admin__field {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 10px;
}

.abnxt-admin__field label {
  width: 80px;
  font-size: 12px;
  color: #374151;
}

.abnxt-admin__input {
  font: inherit;
  padding: 4px 8px;
  border: 1px solid #d1d5db;
  border-radius: 4px;
}

.abnxt-admin__variant {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 6px;
}

.abnxt-admin__variant-key {
  width: 40px;
  font-weight: 600;
}

.abnxt-admin__variant-pct {
  width: 44px;
  text-align: right;
  font-variant-numeric: tabular-nums;
}

.abnxt-admin__sim {
  margin-top: 16px;
}

.abnxt-admin__sim-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 4px;
  font-size: 12px;
}

.abnxt-admin__sim-bar {
  height: 12px;
  background: #2563eb;
  border-radius: 3px;
  min-width: 1px;
}

.abnxt-admin__gate {
  max-width: 360px;
  margin: 48px auto;
  text-align: center;
}

.abnxt-admin__gate-input {
  font: inherit;
  width: 100%;
  padding: 8px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  margin: 12px 0;
}

.abnxt-admin__empty {
  color: #6b7280;
  font-size: 13px;
  padding: 24px;
  text-align: center;
}

.abnxt-admin__error {
  color: #dc2626;
  font-size: 13px;
  margin-top: 8px;
}
</style>

// packages/next/src/admin/AbnxtAdmin.tsx
'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { AbConfig, Experiment } from '@abnxt/core';
import {
  toggleActive,
  setField,
  addExperiment,
  removeExperiment,
  normalizeToPercents,
  addVariant,
  removeVariant,
  setWeight,
  simulateSplit,
  setOverride,
  clearOverride,
  serializeConfig,
  parseConfigJson,
  apiStorage,
} from '@abnxt/core/admin';
import { ADMIN_CSS, ADMIN_STYLE_ID } from './styles';

/** React/Vue 공통 props(형평성: 동일 이름/기본값). */
export interface AbnxtAdminProps {
  /** config GET/PUT 엔드포인트. 기본 '/api/abnxt/config'. */
  configEndpoint?: string;
  /** 키 검증/로그아웃 엔드포인트. 기본 '/api/abnxt/auth'. */
  authEndpoint?: string;
  /** 헤더 타이틀. 기본 'abnxt admin'. */
  title?: string;
}

type AuthState = 'loading' | 'gate' | 'authed';

const EMPTY: AbConfig = { version: 1, experiments: {} };
const SIM_N = 1000;

/** `<style>`를 1회만 주입(중복 마운트/HMR 안전). */
function useInjectStyles(): void {
  useEffect(() => {
    if (typeof document === 'undefined') return;
    if (document.getElementById(ADMIN_STYLE_ID)) return;
    const el = document.createElement('style');
    el.id = ADMIN_STYLE_ID;
    el.textContent = ADMIN_CSS;
    document.head.appendChild(el);
  }, []);
}

/** experiments 레코드의 안정적 key 목록(삽입 순서 유지). */
function expKeys(cfg: AbConfig): string[] {
  return Object.keys(cfg.experiments);
}

export function AbnxtAdmin(props: AbnxtAdminProps) {
  const configEndpoint = props.configEndpoint ?? '/api/abnxt/config';
  const authEndpoint = props.authEndpoint ?? '/api/abnxt/auth';
  const title = props.title ?? 'abnxt admin';

  useInjectStyles();

  const storage = useMemo(
    () => apiStorage({ base: configEndpoint }),
    [configEndpoint],
  );

  const [authState, setAuthState] = useState<AuthState>('loading');
  const [config, setConfig] = useState<AbConfig>(EMPTY);
  const [selectedKey, setSelectedKey] = useState<string | null>(null);
  const [dirty, setDirty] = useState(false);
  const [msg, setMsg] = useState('');
  const [gateError, setGateError] = useState('');
  const [keyInput, setKeyInput] = useState('');
  const [saving, setSaving] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);

  /** config를 GET해 인증 상태를 판별(200=authed, 401=gate, 그 외=메시지 폴백). */
  const fetchConfig = useCallback(async (): Promise<void> => {
    try {
      const res = await fetch(configEndpoint, {
        method: 'GET',
        credentials: 'same-origin',
        headers: { accept: 'application/json' },
      });
      if (res.status === 401) {
        setAuthState('gate');
        return;
      }
      if (!res.ok) {
        setAuthState('gate');
        setGateError(`Failed to load config (${res.status})`);
        return;
      }
      const raw: unknown = await res.json();
      // 렌더 경로 예외 금지: parseConfigJson(검증·폴백) 경유.
      const parsed = parseConfigJson(JSON.stringify(raw));
      setConfig(parsed.config);
      setSelectedKey((prev) => {
        const keys = expKeys(parsed.config);
        if (prev && keys.includes(prev)) return prev;
        return keys[0] ?? null;
      });
      setDirty(false);
      setAuthState('authed');
      if (!parsed.ok && parsed.message)
        setMsg(`Loaded with warning: ${parsed.message}`);
    } catch (err) {
      setAuthState('gate');
      setGateError(err instanceof Error ? err.message : 'Network error');
    }
  }, [configEndpoint]);

  useEffect(() => {
    void fetchConfig();
  }, [fetchConfig]);

  /** 키 제출 → POST auth → 성공 시 config 재GET. */
  const submitKey = useCallback(
    async (e: React.FormEvent): Promise<void> => {
      e.preventDefault();
      setGateError('');
      try {
        const res = await fetch(authEndpoint, {
          method: 'POST',
          credentials: 'same-origin',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ key: keyInput }),
        });
        if (!res.ok) {
          setGateError('Invalid key');
          return;
        }
        setKeyInput('');
        await fetchConfig();
      } catch (err) {
        setGateError(err instanceof Error ? err.message : 'Network error');
      }
    },
    [authEndpoint, keyInput, fetchConfig],
  );

  /** 로그아웃 → DELETE auth → 게이트 복귀. */
  const logout = useCallback(async (): Promise<void> => {
    try {
      await fetch(authEndpoint, {
        method: 'DELETE',
        credentials: 'same-origin',
      });
    } catch {
      /* 만료 실패해도 클라 상태는 게이트로 전환 */
    }
    setConfig(EMPTY);
    setSelectedKey(null);
    setDirty(false);
    setMsg('');
    setAuthState('gate');
  }, [authEndpoint]);

  /** 편집 결과 적용 공통(core 함수가 반환한 새 config). */
  const applyConfig = useCallback((next: AbConfig): void => {
    setConfig(next);
    setDirty(true);
    setMsg('');
  }, []);

  const save = useCallback(async (): Promise<void> => {
    setSaving(true);
    setMsg('');
    try {
      await storage.save(config);
      setDirty(false);
      setMsg('Saved');
    } catch (err) {
      setMsg(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setSaving(false);
    }
  }, [storage, config]);

  const onAddExperiment = useCallback((): void => {
    const next = addExperiment(config);
    // 새로 추가된 key 선택(차집합).
    const before = new Set(expKeys(config));
    const added = expKeys(next).find((k) => !before.has(k));
    applyConfig(next);
    if (added) setSelectedKey(added);
  }, [config, applyConfig]);

  const onExport = useCallback((): void => {
    try {
      const json = serializeConfig(config);
      const blob = new Blob([json], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'abnxt-config.json';
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      setMsg(err instanceof Error ? err.message : 'Export failed');
    }
  }, [config]);

  const onImportFile = useCallback(
    async (e: React.ChangeEvent<HTMLInputElement>): Promise<void> => {
      const file = e.target.files?.[0];
      // 동일 파일 재선택 허용을 위해 input 초기화.
      e.target.value = '';
      if (!file) return;
      try {
        const text = await file.text();
        const parsed = parseConfigJson(text);
        if (!parsed.ok) {
          // 데이터 손실 방지: 검증 실패 시 적용하지 않음.
          setMsg(`Import failed: ${parsed.message ?? 'invalid config'}`);
          return;
        }
        setConfig(parsed.config);
        setSelectedKey(expKeys(parsed.config)[0] ?? null);
        setDirty(true);
        setMsg('Imported (unsaved)');
      } catch (err) {
        setMsg(err instanceof Error ? err.message : 'Import failed');
      }
    },
    [],
  );

  if (authState === 'loading') {
    return (
      <div className="abnxt-admin">
        <div className="abnxt-admin__empty">Loading…</div>
      </div>
    );
  }

  if (authState === 'gate') {
    return (
      <div className="abnxt-admin">
        <form
          className="abnxt-admin__gate"
          onSubmit={submitKey}
        >
          <div className="abnxt-admin__title">{title}</div>
          <p>Enter the admin key to continue.</p>
          <input
            className="abnxt-admin__gate-input"
            type="password"
            value={keyInput}
            onChange={(e) => setKeyInput(e.target.value)}
            placeholder="Admin key"
            aria-label="Admin key"
            autoComplete="current-password"
          />
          <button
            className="abnxt-admin__btn abnxt-admin__btn--primary"
            type="submit"
          >
            Unlock
          </button>
          {gateError ? (
            <div
              className="abnxt-admin__error"
              role="alert"
            >
              {gateError}
            </div>
          ) : null}
        </form>
      </div>
    );
  }

  const keys = expKeys(config);
  const selected =
    selectedKey && config.experiments[selectedKey]
      ? config.experiments[selectedKey]
      : null;

  return (
    <div className="abnxt-admin">
      <input
        ref={fileInputRef}
        type="file"
        accept="application/json,.json"
        style={{ display: 'none' }}
        onChange={onImportFile}
        data-testid="abnxt-import-input"
      />
      <header className="abnxt-admin__header">
        <div className="abnxt-admin__title">{title}</div>
        <button
          className="abnxt-admin__btn"
          type="button"
          onClick={onAddExperiment}
        >
          + Experiment
        </button>
        <button
          className="abnxt-admin__btn"
          type="button"
          onClick={onExport}
        >
          Export
        </button>
        <button
          className="abnxt-admin__btn"
          type="button"
          onClick={() => fileInputRef.current?.click()}
        >
          Import
        </button>
        <button
          className={
            'abnxt-admin__btn' + (dirty ? ' abnxt-admin__btn--dirty' : '')
          }
          type="button"
          onClick={() => void save()}
          disabled={!dirty || saving}
        >
          Save
        </button>
        <button
          className="abnxt-admin__btn"
          type="button"
          onClick={() => void logout()}
        >
          Logout
        </button>
      </header>

      {msg ? (
        <div
          className="abnxt-admin__msg"
          role="status"
        >
          {msg}
        </div>
      ) : null}

      <div className="abnxt-admin__body">
        <ExperimentList
          config={config}
          keys={keys}
          selectedKey={selectedKey}
          onSelect={setSelectedKey}
          onToggle={(k) => applyConfig(toggleActive(config, k))}
        />
        {selected && selectedKey ? (
          <ExperimentEditor
            expKey={selectedKey}
            experiment={selected}
            config={config}
            onApply={applyConfig}
            onDelete={(k) => {
              const next = removeExperiment(config, k);
              applyConfig(next);
              setSelectedKey(expKeys(next)[0] ?? null);
            }}
            onMessage={setMsg}
          />
        ) : (
          <div className="abnxt-admin__empty">
            No experiment selected. Add one to begin.
          </div>
        )}
      </div>
    </div>
  );
}

interface ListProps {
  config: AbConfig;
  keys: string[];
  selectedKey: string | null;
  onSelect: (key: string) => void;
  onToggle: (key: string) => void;
}

function ExperimentList(props: ListProps) {
  if (props.keys.length === 0) {
    return (
      <div className="abnxt-admin__list">
        <div className="abnxt-admin__empty">No experiments yet.</div>
      </div>
    );
  }
  return (
    <div className="abnxt-admin__list">
      {props.keys.map((key) => {
        const exp = props.config.experiments[key];
        const split = exp.variants.map((v) => v.key).join('/');
        const selected = key === props.selectedKey;
        return (
          <div
            key={key}
            className={
              'abnxt-admin__list-item' +
              (selected ? ' abnxt-admin__list-item--selected' : '')
            }
            onClick={() => props.onSelect(key)}
          >
            <div className="abnxt-admin__list-main">
              <span className="abnxt-admin__list-name">{exp.name}</span>
              <span className="abnxt-admin__list-key">{key}</span>
              <span className="abnxt-admin__list-split">{split}</span>
            </div>
            <button
              className="abnxt-admin__btn"
              type="button"
              onClick={(e) => {
                e.stopPropagation();
                props.onToggle(key);
              }}
            >
              {exp.active ? 'on' : 'off'}
            </button>
          </div>
        );
      })}
    </div>
  );
}

interface EditorProps {
  expKey: string;
  experiment: Experiment;
  config: AbConfig;
  onApply: (next: AbConfig) => void;
  onDelete: (key: string) => void;
  onMessage: (msg: string) => void;
}

function ExperimentEditor(props: EditorProps) {
  const { expKey, experiment, config } = props;

  // 변이별 % (정규화) — 표시 전용, 항상 합 100.
  const percents = useMemo(
    () => normalizeToPercents(experiment.variants),
    [experiment.variants],
  );

  // 시뮬레이션 분배(1000명). 렌더 경로 예외 금지를 위해 try/catch 폴백.
  const sim = useMemo<Record<string, number>>(() => {
    try {
      return simulateSplit(experiment, SIM_N);
    } catch {
      return {};
    }
  }, [experiment]);
  const simMax = Math.max(1, ...Object.values(sim));

  /** variants를 갈아끼운 새 config 적용(setField가 variants를 다루지 않으므로 upsert 경유). */
  const applyVariants = useCallback(
    (variants: Experiment['variants']): void => {
      props.onApply({
        ...config,
        experiments: {
          ...config.experiments,
          [expKey]: { ...experiment, variants },
        },
      });
    },
    [config, expKey, experiment, props],
  );

  return (
    <div className="abnxt-admin__editor">
      <div className="abnxt-admin__field">
        <label htmlFor="abnxt-f-name">name</label>
        <input
          id="abnxt-f-name"
          className="abnxt-admin__input"
          type="text"
          value={experiment.name}
          onChange={(e) =>
            props.onApply(setField(config, expKey, { name: e.target.value }))
          }
        />
      </div>

      <div className="abnxt-admin__field">
        <label htmlFor="abnxt-f-active">active</label>
        <input
          id="abnxt-f-active"
          type="checkbox"
          checked={experiment.active}
          onChange={() => props.onApply(toggleActive(config, expKey))}
        />
      </div>

      <div className="abnxt-admin__field">
        <label htmlFor="abnxt-f-sticky">sticky</label>
        <input
          id="abnxt-f-sticky"
          type="checkbox"
          checked={experiment.sticky}
          onChange={(e) =>
            props.onApply(
              setField(config, expKey, { sticky: e.target.checked }),
            )
          }
        />
      </div>

      <div className="abnxt-admin__field">
        <label htmlFor="abnxt-f-seed">seed</label>
        <input
          id="abnxt-f-seed"
          className="abnxt-admin__input"
          type="text"
          value={experiment.seed}
          onChange={(e) =>
            props.onApply(setField(config, expKey, { seed: e.target.value }))
          }
        />
      </div>

      <div className="abnxt-admin__field">
        <label htmlFor="abnxt-f-control">control</label>
        <select
          id="abnxt-f-control"
          className="abnxt-admin__input"
          value={experiment.control}
          onChange={(e) =>
            props.onApply(setField(config, expKey, { control: e.target.value }))
          }
        >
          {experiment.variants.map((v) => (
            <option
              key={v.key}
              value={v.key}
            >
              {v.key}
            </option>
          ))}
        </select>
      </div>

      <div className="abnxt-admin__field">
        <label>variants</label>
      </div>
      {experiment.variants.map((v) => (
        <div
          key={v.key}
          className="abnxt-admin__variant"
        >
          <span className="abnxt-admin__variant-key">{v.key}</span>
          <input
            className="abnxt-admin__input"
            type="range"
            min={0}
            max={100}
            value={v.weight}
            aria-label={`weight ${v.key}`}
            onChange={(e) =>
              applyVariants(
                setWeight(experiment.variants, v.key, Number(e.target.value)),
              )
            }
          />
          <span className="abnxt-admin__variant-pct">
            {percents[v.key] ?? 0}%
          </span>
          <button
            className="abnxt-admin__btn"
            type="button"
            onClick={() => setOverride(expKey, v.key)}
          >
            Preview
          </button>
          <button
            className="abnxt-admin__btn"
            type="button"
            onClick={() => clearOverride(expKey)}
          >
            Clear
          </button>
          <button
            className="abnxt-admin__btn abnxt-admin__btn--danger"
            type="button"
            aria-label={`remove ${v.key}`}
            onClick={() =>
              applyVariants(removeVariant(experiment.variants, v.key))
            }
          >
            ✕
          </button>
        </div>
      ))}
      <div className="abnxt-admin__field">
        <button
          className="abnxt-admin__btn"
          type="button"
          onClick={() => applyVariants(addVariant(experiment.variants))}
        >
          + Variant
        </button>
      </div>

      <div className="abnxt-admin__sim">
        <strong>Simulation ({SIM_N})</strong>
        {experiment.variants.map((v) => {
          const count = sim[v.key] ?? 0;
          const pct = Math.round((count / SIM_N) * 100);
          return (
            <div
              key={v.key}
              className="abnxt-admin__sim-row"
            >
              <span className="abnxt-admin__variant-key">{v.key}</span>
              <span
                className="abnxt-admin__sim-bar"
                style={{ width: `${(count / simMax) * 200}px` }}
              />
              <span className="abnxt-admin__variant-pct">{pct}%</span>
            </div>
          );
        })}
      </div>

      <div
        className="abnxt-admin__field"
        style={{ marginTop: 16 }}
      >
        <button
          className="abnxt-admin__btn abnxt-admin__btn--danger"
          type="button"
          onClick={() => props.onDelete(expKey)}
        >
          Delete
        </button>
      </div>
    </div>
  );
}
